const AboutData=[
  {
  "id": 1,
  "name": "time ",
  "title": "Ecplore the freight service",
  "details":"Lorem ipsum dolor sit amet consectetur luptatum aliquid doloribus qui, quis perferendis fuga voluptatem blanditiis quidem temporibus accusamus ab a? Iure explicabo cupiditate ipsum nulla architecto praesentium facere fugiat possimus quas in. Optio incidunt accusantium aliquid fuga minima iure, beatae mollitia blanditiis molestiae commodi alias recusandae id in itaque eligendi neque earum quis delectus laudantium repudiandae",
  "benifit1": "Lorem ipsum dolor sit amet",
  "benifit2": "elit. Corporis ipsum voluptas sunt",
  "benifit3": "temporibus accusamus ab a?",
  "benifit4": "architecto praesentium facere fugiat possimus quas in",
  "benifit5": "beatae mollitia blanditiis molestiae commodi",
  "benifit6": "accusantium aliquid fuga minima iure",
  "img": "https://i.ibb.co/FDKC3tC/time.jpg",
  "icon": "FiPhoneCall",
},
  {
  "id": 2,
  "name": "world wide",
  "title": "Where ever you want",
  "details":"Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis ipsum voluptas sunt voluptatum aliquid doloribus qui, quis perferendis fuga voluptatem blanditiis quidem temporibus accusamus ab a? Iure explicabo cupiditate ipsum nulla architecto praesentium facere fugiat possimus quas in. Optio incidunt accusantium aliquid fuga minima iure, beatae mollitia blanditiis molestiae commodi alias recusandae id in itaque eligendi neque earum quis delectus laudantium repudiandae",
  "benifit1": "ipsum voluptas sunt voluptatum",
  "benifit2": "elit. voluptas sunt",
  "benifit3": "temporibus accusamus ab a?",
  "benifit4": "architecto  possimus quas in",
  "benifit5": "blanditiis molestiae commodi",
  "benifit6": "accusantium  iure",
  "img": "https://i.ibb.co/NyLshTX/world-Wide.jpg"
},
  {
  "id": 3,
  "name": "Delivery ",
  "title": "Explore our vehicles",
  "details":"Lorem ipsum dolor sit amet caliquid doloribus qui, quis perferendis fuga voluptatem blanditiis quidem temporibus accusamus ab a? Iure explicabo cupiditate ipsum nulla architecto praesentium facere fugiat possimus quas in. Optio incidunt accusantium aliquid fuga minima iure, beatae mollitia blanditiis molestiae commodi alias recusandae id in itaque eligendi neque earum quis delectus laudantium repudiandae",
  "benifit1": "Lorem ipsum  amet",
  "benifit2": "elit. Corporis ipsum voluptas sunt",
  "benifit3": "temporibus accusamus ab a?",
  "benifit4": "architecto  facere fugiat possimus quas in",
  "benifit5": "beatae mollitia blanditiis ",
  "benifit6": "accusantiumfuga minima iure",
  "img": "https://i.ibb.co/10Wy1L8/truck.jpg"
},
  {
  "id": 4,
  "name": "fourth ",
  "title": "Fastest service what ever you want",
  "details":"Lorem ipsum dolor sit amet consectetur itiis quidem temporibus accusamus ab a? Iurum nulla architecto praesentium facere fugiat possimus quas in. Optio incidunt accusantium aliquid fuga minima iure, beatae mollitia blanditiis molestiae commodi alias recusandae id in itaque eligendi neque earum quis delectus laudantium repudiandae",
  "benifit1": "Lorem olor sit amet",
  "benifit2": "elit.ptas sunt",
  "benifit3": "temporibus accusamus ab a?",
  "benifit4": "architectsimus quas in",
  "benifit5": "beatae mollitia blanditiis molestiae commodi",
  "benifit6": "accusantiuga minima iure",
  "img": "https://i.ibb.co/FDKC3tC/time.jpg"
},
  {
  "id": 5,
  "name": "fifth ",
  "title": "Fully dedicated team",
  "details":"Lorem ipsum dolor sit ameta voluptatem blanditiis quidem upiditate ipsum nulla architecto praesentium facere fugiat possimus quas in. Optio incidunt accusantium aliquid fuga minima iure, beatae mollitia blanditiis molestiae commodi alias recusandae id in itaque eligendi neque earum quis delectus laudantium repudiandae",
  "benifit1": "Lorem sit amet",
  "benifit2": "elit. Corporoluptas sunt",
  "benifit3": "temporibus accusamus ab a?",
  "benifit4": "architecacere fugiat possimus quas in",
  "benifit5": "beataeiae commodi",
  "benifit6": "accusantium aliquid fuga minima iure",
  "img": "https://i.ibb.co/qnbRfX3/team.jpg",
}
]
export default AboutData